//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorEDI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsPayable
    {
        public long Id { get; set; }
        public string VendorName { get; set; }
        public string VendorNumber { get; set; }
        public string CheckNumber { get; set; }
        public string BatchNumber { get; set; }
        public string OrderNumber { get; set; }
        public string VendorOrderInvoiceNumber { get; set; }
        public string SknId { get; set; }
        public string VendorSkuCode { get; set; }
        public long UnitsShipped { get; set; }
        public long VendorItemCost { get; set; }
        public long VendorShippingCost { get; set; }
        public long VendorHandlingCost { get; set; }
        public long ItemCost { get; set; }
        public long TotalCost { get; set; }
        public long VendorTotalCost { get; set; }
    }
}
